# Stage 1: Сборка приложения
FROM node:18 AS builder

# Задаём рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файлы зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходный код
COPY . .

# Собираем проект (создаётся папка dist)
RUN npm run build


# Stage 2: Запуск приложения
FROM node:18

WORKDIR /app

# Копируем необходимые файлы из этапа сборки
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

# Открываем порт, на котором работает приложение (по умолчанию NestJS использует 3000)
EXPOSE 3000

# Команда для запуска production-сборки
CMD ["npm", "run", "start:prod"]